### ISSUE TITLE
Dynamo Component

### ISSUE THREAD

**Issue by alfarok** [HydraShare/hydra#10]
Collaborate to finish the Dynamo Component

[mjkkirschner](https://github.com/mjkkirschner) provided this sample that illustrates saving the graph on button press which could be made simpler and hook up the callback that saves the graph to the evaluation event on the node so it will just save the file on every run of the graph etc..

https://github.com/mjkkirschner/DynamoSamples/blob/hydranodesample/src/SampleLibraryUI/Examples/CustomNodeModel.cs

**Comment by alfarok** [comment]
![image](https://cloud.githubusercontent.com/assets/13341935/10205376/dc908148-678e-11e5-9c69-1d36d17b55b3.png)

**Comment by mjkkirschner** [comment]
if anyone takes this on and needs assistance feel free to email or ping me

**Comment by mostaphaRoudsari** [comment]
@alfarok nice job with the node and the [new example](http://hydrashare.github.io/hydra/viewer?owner=alfarok&fork=hydra&id=DynamoTest1)! Congratulations. I have one minor comment about the download file. Can you zip the file? It will be both consistent with Grasshopper component and at some point users can also share REVIT files associated with the .dyn file. Now if the user clicks on the link it will open up the xml file in the browser instead of downloading it. It can be confusing for novice users.

**Comment by mjkkirschner** [comment]
@alfarok look at System.IO.Compression.Filesystem.ZipFile

**Comment by alfarok** [comment]
@mostaphaRoudsari  @mjkkirschner  Thank you Mike!  I was having trouble figuring out how to zip the files without using a 3rd party reference in .NET 4.0 which is why it was just generating a .dyn file.  There is still a lot of cleanup to make the Dynamo node as organized and logical as the Grasshopper version but I wanted to get a basic working prototype up that we could build off of.  I am looking at different screen capture options now to capture the model as well.

**Comment by alfarok** [comment]
@mjkkirschner I actually just realized is Dynamo 0.9 using .NET 4.5?  I couldn't use ZipFile.CreateFromDirectory because it didn't exist in .NET 4.0 I don't think.

**Comment by mjkkirschner** [comment]
yes, you need to add a reference to System.IO.Compression and System.IO.Compression.FileSystem, and we have moved to .net 4.5 some time ago. (.9 timeframe)

**Comment by alfarok** [comment]
Updated the example with the zipped file.  I think I am going to close this thread now and open individual threads for the things that need to be added/fixed.

**Comment by mostaphaRoudsari** [comment]
@alfarok Congrats. Sounds great! Please do.

**Comment by mostaphaRoudsari** [comment]
@mjkkirschner thanks for the support.

**Comment by alfarok** [comment]
I am going to fix a few more issues that I know of this weekend and I will post to the package manager Monday morning.
