### ISSUE TITLE
GH files missing

### ISSUE THREAD

**Issue by ayezioro** [HydraShare/hydra#14]
Hi,
I've found at least three examples where the GH definition is not found. It happens that those 2 are coming from Mostapha. So maybe some changes happen and they GH is not uploaded anymore.
So FYI in case this is true or sorry if it isn't.
The examples are the Room Orientation Optimization, Shadow Range Study and Remove Glazing Honeybee example.
Thanks,
-A.

**Comment by mostaphaRoudsari** [comment]
Thanks @ayezioro! As far as I can see the download button is broken. The grasshopper component should still work fine. Remove Galzing is using the old version. Let me check and I will get back to you soon.

**Comment by mostaphaRoudsari** [comment]
Guess who's mistake was that. ;) I just get it fixed. It should work fine now. Thanks for reporting.

**Comment by ayezioro** [comment]
I'm guessing ... i'm guessing.
Thanks,
-A.
