### ISSUE TITLE
Grasshopper component should have Grasshopper as default tag, so as Dynamo for Dynamo

### ISSUE THREAD

**Issue by mostaphaRoudsari** [HydraShare/hydra#16]
In case user hasn't provide the template as a tag the component/node needs to add it to the end of the list as default.

cc: @alfarok @chriswmackey

**Comment by mostaphaRoudsari** [comment]
@alfarok I addressed this for Grasshopper. Can you make sure to address this in Dynamo node? Looking forward to the first dynamo example on Hydra. :balloon:

**Comment by alfarok** [comment]
added "Dynamo" as default tag.
