### ISSUE TITLE
Dynamo/Grasshopper Organization

### ISSUE THREAD

**Issue by alfarok** [HydraShare/hydra#24]
Now that Hydra is supporting Dynamo and Grashopper I was wondering how we want to organize the overlap.  Here are a few issues that come to mind.

-Separating installation files/code on multiple GitHub pages
-Naming conventions (I had to use some of the Grasshopper conventions to have things  load properly to the web)
-Old version of Hydra error message (all Dynamo files will show this)

I am sure there are a lot more topics but I figured we could just brainstorm a few ideas of the approach we might take.

**Comment by mostaphaRoudsari** [comment]
Hi @alfarok. Very good points.
- I made two separate repositories for Grasshopper and Dynamo plugin/add on. You can push all the files related to Dynamo node to hydra-dynamo
- For the next two are you need to follow the [latest structure](https://github.com/HydraShare/hydra/wiki/Hydra-Schema-and-Folder-Structure). I was see this coming so I changed the structure to be the same for both platforms.

Let me know if it answers your questions. Is the node already available as a package in Dynamo package manager?

**Comment by alfarok** [comment]
@mostaphaRoudsari  Awesome!  I will work on getting everything uploaded and in place.  I will also check  out the new structure and need to clean the code up, I was just looking to get a basic working version up as fast as possible to start building off of.  The node is uploaded to the Dynamo package manager for download built off Dynamo version 0.9
