### ISSUE TITLE
connection to DynamoWorks

### ISSUE THREAD

**Issue by LukeyJohnson** [HydraShare/hydra#28]
Hi, would you like to be an admin at dynamoworks and post about Hydra nodes for Dynamo when they become available. If you would like, send me your email address and I will invite you.

Ideally, we could find a way to integrate graph sharing, with wiki, with packages, with node based content like on DynamoWorks.

**Comment by alfarok** [comment]
Hey @LukeyJohnson , we currently do have an early version of Hydra for Dynamo you can download from the package manager and check out [here](https://github.com/HydraShare/hydra-dynamo) on github.  It sounds like an interesting idea and I am definitely interested in helping out.  If you would still like hydra updates posted to DynamoWorks I have no problem doing that as well.  keith4895@gmail.com

**Comment by LukeyJohnson** [comment]
Ok cool I have invited you to the Wordpress and Asana sites.
