### ISSUE TITLE
Not all examples are being displayed for a given fork

### ISSUE THREAD

**Issue by alfarok** [HydraShare/hydra#37]
I have noticed that various examples are missing when we refresh the repo data.  I believe the data is refreshed a couple of times per hour but it appears the data that comes back is not consistent as some of my examples are randomly hidden hour to hour.  It appears the bug is that not all folders in each fork are properly pulled and posted.

**Comment by mostaphaRoudsari** [comment]
Hi @alfarok, It happens when we reach the maximum number of GitHub API calls.
See this: https://github.com/HydraShare/hydra/issues/33
