### ISSUE TITLE
hydrashare.github.io not loading

### ISSUE THREAD

**Issue by sam-dreams-of-buildings** [HydraShare/hydra#44]
apologies if this is covered in another issue post.

when i navigate to http://hydrashare.github.io/hydra/ the page fully loads and nothing comes up. 

there's just a bit of text at the top that says "Loading; one moment please" that never loads.

**Comment by mostaphaRoudsari** [comment]
I tested Hydra on different browsers and it is working fine. If the issue happened again can you you go to browser developer console and take a screenshot of the errors?
